Basic update

diff --git a/wrappers/.local/bin/rebar3 b/wrappers/.local/bin/rebar3
--- a/wrappers/.local/bin/rebar3
+++ b/wrappers/.local/bin/rebar3
@@ -5,9 +5,9 @@ if ! command -v erl >/dev/null 2>&1; then
     exit 1
 fi
 
-if [[ -x ~/.cache/rebar3/bin/rebar3 ]]; then
-    echo "Cannot find rebar3 in '~/.cache/rebar3/bin/rebar3'!" >&2
+if [[ ! -x /home/ssoss/.local/libexec/rebar3 ]]; then
+    echo "Cannot find rebar3 in '/home/ssoss/.local/libexec/rebar3'" >&2
     exit 1
 fi
 
-~/.cache/rebar3/bin/rebar3 "$@"
+exec -a "$0" /home/ssoss/.local/libexec/rebar3 "$@"
